stages:
  collect:
    cmd: python src/data_collection.py
    deps:
      - src/data_collection.py
    outs:
      - data/raw/
  clean:
    cmd: python src/data_cleaning.py
    deps:
      - src/data_cleaning.py
      - data/raw/
    outs:
      - data/cleaned/
  detect:
    cmd: python src/object_detection.py
    deps:
      - src/object_detection.py
      - data/images/
    outs:
      - data/detections/
